### ISSUE TITLE
Add public CI configuration for public PRs

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#181]
Our current VSTS configs don't build community PRs. We need to add that; a lot like what Blazor has:

https://github.com/aspnet/Blazor/blob/master/.azure/pipelines/ci-public.yml

We'll have to add the vsts files + add a definition to dev.azure.com/dnceng/public

@SteveSandersonMS giving this to you since it's there for Blazor + you set the definitions up for our normal vsts builds.

**Comment by SteveSandersonMS** [comment]
Done: https://dnceng.visualstudio.com/public/_build?definitionId=212
