### ISSUE TITLE
Blazor support?

### ISSUE THREAD

**Issue by seriouz** [aspnet/Razor.VSCode#188]
#### Is this a Bug or Feature request?: Feature 

Will Blazor be supported, or is it already in work to be supported?

**Comment by NTaylorMullen** [comment]
> Will Blazor be supported, or  is it already in work to be supported?

It's not currently supported but we do plan to add support for Blazor. 

Right now (no promises) I'd keep an eye on the alpha 2 Razor VSCode release. What's currently planned will enable us to get a very basic Blazor experience. All that being said, alpha2 is a few months out, a lot can happen between now and then, so stay tuned 😉!

Leaving this open for any others who are curious.

**Comment by seriouz** [comment]
Thanks for clearing up!

**Comment by danroth27** [comment]
We expect to add C# and directive completions for Blazor apps in alpha 1, but there will be no support for tag helpers or blazor components. As a result, Blazor apps will likely display some false errors for our first release. We plan to address this for alpha2 as @NTaylorMullen indicated.

**Comment by danroth27** [comment]
Closing this issue as the question was answered and we are tracking the work with other issues.
