### ISSUE TITLE
Incorrect completion in a simple view page

### ISSUE THREAD

**Issue by akshita31** [aspnet/Razor.VSCode#210]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
Open a simple ASP.NET application like the one [here](https://github.com/akshita31/ASP.NET-Learning-Sample/blob/v1.0/WebApplication1/Views/Home/Index.cshtml#L1) the project here and type @model SampleApplication.Models.

#### Description of the problem:
Unexpected completion when typing Models. in continuation. When typing just "." after Models then the expected completion is shown.

Expected behavior:
Only Restaurants is shown in the completion

Actual behavior:
"models" is shown in completions which is unexpected
![razor](https://user-images.githubusercontent.com/12554141/47282806-7552bc80-d595-11e8-91ee-8bd8a5271a88.gif)

#### Additional information

1. Razor C# output
[razorCSharp.txt](https://github.com/aspnet/Razor.VSCode/files/2500544/razorCSharp.txt)

2. Razor log Output
[razorLog.txt](https://github.com/aspnet/Razor.VSCode/files/2500527/razorLog.txt)

4. OmniSharp log output
[omnisharpLog.txt](https://github.com/aspnet/Razor.VSCode/files/2500533/omnisharpLog.txt)

**Comment by NTaylorMullen** [comment]
Seeing this more frequently now, diagnosing it a little bit it looks like an issue on the OmniSharp side. Need to dive a little deeper but basically OmniSharp is returning completion info for an outdated document.

**Comment by akshita31** [comment]
@NTaylorMullen It just shows the plural of whatever preceeds the dot. I randomly tried SampleApplication.Services. and it showed "services" as the suggestion

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen It just shows the plural of whatever preceeds the dot. I randomly tried SampleApplication.Services. and it showed "services" as the suggestion

You mean the lowercase variant?

**Comment by akshita31** [comment]
Lowercase variant as well as plural. For "abc", I am getting "abcs"

**Comment by NTaylorMullen** [comment]
> Lowercase variant as well as plural. For "abc", I am getting "abcs"

Ahhh, good to know. Must be another completion provider in VSCode providing that. Good catch @akshita31 !

**Comment by NTaylorMullen** [comment]
> Also, I have a question. If I am in the middle of a session and I change the Razor log level, to the best of my understanding, the change is not reflected until we restart code completely. Is there a possibilty that we expose a command like "Restart Razor language server" the same way we do for omnisharp?

Definitely on the roadmap for alpha2 😄. It'll be added as part of [this](https://github.com/aspnet/Razor.VSCode/issues/34) issue.

**Comment by NTaylorMullen** [comment]
f9323c9bcbdf9b891def11327a7eeede0fcd89e3
