### ISSUE TITLE
CSharp intellisense isn't always correct

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#215]
Trying to get intellisense after the `DateTime.`. The correct only shows up occasionally. Below is me trying to invoke intellisense by entering dot and then retrying after a backspace. As you can see, the correct intellisense only showed up twice out of 11 attempts.

![image](https://media.giphy.com/media/BLLZgvgXMzQFoMua3L/giphy.gif)

VS Code version: 1.28.2 
Omnisharp version: 1.17.0-beta7
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 2.2.100-preview2-009404

**Comment by danroth27** [comment]
This seems to happen only on the line prior to the closing curly brace and you're dealing with an expression.

**Comment by NTaylorMullen** [comment]
f9323c9bcbdf9b891def11327a7eeede0fcd89e3
