### ISSUE TITLE
Directive intellisense is sometimes shown for attributes

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#216]
Similar to #215, it doesn't happen consistently.

![image](https://media.giphy.com/media/5toyw1fm7g3rHq1rHK/giphy.gif)

VS Code version: 1.28.2
Omnisharp version: 1.17.0-beta7
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 2.2.100-preview2-009404

**Comment by NTaylorMullen** [comment]
Root cause is dup of #215
