### ISSUE TITLE
No errors for duplicate directives

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#217]
I'm not sure if this is a known limitation but there are no errors shown for duplicate directives as well as directives that are not at the start of line.

![image](https://user-images.githubusercontent.com/1579269/47591190-813ad780-d923-11e8-95ac-eadf84ec032b.png)

VS Code version: 1.28.2
Omnisharp version: 1.17.0-beta7
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 2.2.100-preview2-009404

**Comment by danroth27** [comment]
Dup of https://github.com/aspnet/Razor.VSCode/issues/30
