### ISSUE TITLE
HTML intellisense initially off by one character

### ISSUE THREAD

**Issue by danroth27** [aspnet/Razor.VSCode#218]
After installing the C# extension I created a new ASP.NET Core 2.2 web app. I then tried adding an h1 tag to the Index.cshtml page and I got this:

![image](https://user-images.githubusercontent.com/1874516/47804835-0d1d7c80-dcf3-11e8-836e-7ad82f532766.png)

When I typed the "l" in "class" I then got completions starting with "l". 

After a short while (a few min?) I could no longer reproduce the behavior.

**Comment by danroth27** [comment]
Unfortunately, no. I restarted VS Code when I was trying to reproduce the issue.

**Comment by NTaylorMullen** [comment]
f9323c9bcbdf9b891def11327a7eeede0fcd89e3
