### ISSUE TITLE
Consider: Don't start razor language service when there are no razor files

### ISSUE THREAD

**Issue by gregg-miskelly** [aspnet/Razor.VSCode#222]
_From @gregg-miskelly on November 2, 2018 22:51_

## Environment data
C# Extension version: 1.17

## Steps to reproduce
1. Create a new C# .NET Core console app
2. Open the folder in VS Code

## Expected  behavior
Razor language service (rzls) process shouldn't start since there are no razor files

## Actual behavior
Razor language service starts

_Copied from original issue: OmniSharp/omnisharp-vscode#2649_

**Comment by gregg-miskelly** [comment]
_From @NTaylorMullen on November 2, 2018 22:54_

This is definitely a reasonable request. @gregg-miskelly would you mind filing the issue over in https://github.com/aspnet/Razor.VSCode?

**Comment by gregg-miskelly** [comment]
I can move it using https://github-issue-mover.appspot.com

**Comment by NTaylorMullen** [comment]
86b17fa24f45ae0cddbce9b93f3bc583150d1b0d
