### ISSUE TITLE
Razor error: libunwind.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by walkjivefly** [aspnet/Razor.VSCode#223]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
Open VSCode in a new dotnet project directory.

#### Description of the problem:
Razor log displayed saying
```
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha1-20181019.5
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

Failed to load .^, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mark/.vscode/extensions/ms-vscode.csharp-1.17.0/.razor/libcoreclr.so'
[Error - 18:12:19] Connection to server is erroring. Shutting down server.
[Error - 18:12:19] Connection to server is erroring. Shutting down server.
[Error - 18:12:19] Connection to server is erroring. Shutting down server.
```
Expected behavior:
Not a  bunch of error messages from something I didn't explicitly install or want. 
Actual behavior:
Bunch of error messages from something I've never heard of.
#### Additional information
I'm a C# and VSCode newbie. Installed it. Installed C# and Omnisharp extensions. Created a new dotnet  skeleton project. Started VSCode from the projet directory. 
 I didn't ask it for Razor. I have no idea what Razor is and I don't want to know either.

Please also provide the following to help debug the issue:

1. Razor (cshtml) file content: I don't have one.
2. Generated C# code from the Razor CSharp Output in VS Code. See #1 above
3. Verbose Razor log output. See problem description above
4. OmniSharp log output:
```
Starting OmniSharp server at 03/11/2018, 18:12:19
    Target: /home/mark/src/crap

OmniSharp server started with Mono 5.16.0.
    Path: /home/mark/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/OmniSharp.exe
    PID: 18282

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on debian 9.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/mark/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /home/mark/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/mark/src/crap'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/mark/src/crap'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/mark/src/crap/crap.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/mark/src/crap'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/mark/src/crap' on host 18177.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/mark/src/crap/crap.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/mark/src/crap/crap.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/mark/src/crap/crap.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: crap
```
Someone already reported (probably) the same thing: 
```
Consider: Don't start razor language service when there are no razor files #222
```
 but the issue was closed with a comment to open an issue in https://github.com/aspnet/Razor.VSCode - which is exactly where it was, and where this is.

**Comment by NTaylorMullen** [comment]
@walkjivefly sorry that you're running into this! What platform did you encounter this on? (flavor of linux? x86/x64?)

**Comment by walkjivefly** [comment]
It's MX 17.1 distro, x64 machine. 
It's just annoying when something I didn't ask for 
1. spits out noise messages
2. complains about stuff that's not installed

**Comment by NTaylorMullen** [comment]
@walkjivefly I totally understand. This is something we plan to address.

**Comment by NTaylorMullen** [comment]
By the way you can work around this by setting `razor.disabled` to `true` in your settings.

**Comment by danroth27** [comment]
We plan to address this by not running the Razor language service when there are no Razor files in the project: #222

**Comment by walkjivefly** [comment]
Thanks for the workaround. Now if only I could get the debugger to to something....

**Comment by matjaz132** [comment]
Same error on Debian Stable 9.6

Any fix other than disabling Razor? I'm just starting on C#

**Comment by danroth27** [comment]
@matjaz132 What version of the C# extension do you have installed? Does disabling Razor address help?

**Comment by matjaz132** [comment]
The default one from vscode extension shop. Disabling razer feature helps.

**Comment by danroth27** [comment]
@matjaz132 Could you please share the exact version number? You can find it in the extensions tab:

![image](https://user-images.githubusercontent.com/1874516/49175652-f2dcbb80-f2fd-11e8-9d56-75d1ca8d5480.png)

**Comment by danroth27** [comment]
Cool, thx, that's the latest version.

**Comment by walkjivefly** [comment]
Debugging is working with 1.17.1 without disabling Razor. 
Thank you.

**Comment by gayanW** [comment]
I have C# 1.17.1. But still had to disable Razor. (Debian 9)

**Comment by NTaylorMullen** [comment]
> I have C# 1.17.1. But still had to disable Razor. (Debian 9)

So debugging did not work unless you disabled Razor?

**Comment by walkjivefly** [comment]
Wearing egg on face here. After restarting VSCode with Razor enabled, debugging stopped working again. I do need Razor disabled for debugging to work. Even with 1.17.1
Sorry for posting duff info 4 days ago.

**Comment by gayanW** [comment]
> > I have C# 1.17.1. But still had to disable Razor. (Debian 9)
> 
> So debugging did not work unless you disabled Razor?

Yes. And the Razor error is displayed at the startup.

**Comment by NTaylorMullen** [comment]
@gregg-miskelly any idea why Razor would impact debugging in any way?

**Comment by gregg-miskelly** [comment]
@NTaylorMullen will a razor startup failure cause an activation failure of the entire C# extension?

**Comment by NTaylorMullen** [comment]
> will a razor startup failure cause an activation failure of the entire C# extension?

No, [we try-catch](https://github.com/aspnet/Razor.VSCode/blob/527c91929f5481b2722245609fbee00efdbc33ec/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts#L32-L100) around our activation logic. The only way that could occur is if some of the bootstrapping code itself (code in omnisharp-vscode) threw an exception. Based off your assumption would they experience other C# related failures assuming the C# experience didn't properly activate?

**Comment by gregg-miskelly** [comment]
If the C# extension properly activated then debugging should be unaffected by a Razor startup failure.

**Comment by gayanW** [comment]
**Razor Log**
```
Razor.VSCode version 1.0.0-alpha2-20181112.3
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Verbose'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

[Client - 10:22:30 AM] Starting Razor Language Server...
[Client - 10:22:30 AM] Server started, waiting for client to be ready...
Failed to load �?, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/gayan/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/libcoreclr.so'
[Error - 10:22:31 AM] Connection to server is erroring. Shutting down server.
[Error - 10:22:31 AM] Connection to server is erroring. Shutting down server.
[Error - 10:22:31 AM] Connection to server is erroring. Shutting down server.
```

**OmniSharp Log**
```
Starting OmniSharp server at 12/5/2018, 10:22:31 AM
    Target: /home/gayan/unity-projects/Gravity/Gravity.sln

OmniSharp server started with Mono 5.16.0.
    Path: /home/gayan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe
    PID: 2872

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on debian 9.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/gayan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /home/gayan/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/gayan/unity-projects/Gravity'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/gayan/unity-projects/Gravity/Gravity.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/gayan/unity-projects/Gravity/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/gayan/unity-projects/Gravity/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/gayan/unity-projects/Gravity'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/gayan/unity-projects/Gravity' on host 2784.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/gayan/unity-projects/Gravity/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/gayan/unity-projects/Gravity/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/gayan/unity-projects/Gravity/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/gayan/unity-projects/Gravity/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/gayan/unity-projects/Gravity/Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/gayan/unity-projects/Gravity/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/home/gayan/unity-projects/Gravity/Temp/bin/Debug/Assembly-CSharp.dll'
```

**Comment by walkjivefly** [comment]
I remembered to restart VSCode between config changes this time. With razor disabled:
[razor_disabled_dotnettest.log](https://github.com/aspnet/Razor.VSCode/files/2647251/razor_disabled_dotnettest.log)
[razor_disabled_omnisharp.log](https://github.com/aspnet/Razor.VSCode/files/2647252/razor_disabled_omnisharp.log)
With razor enabled and verbose logging:
[razor_enabled_dotnettest.log](https://github.com/aspnet/Razor.VSCode/files/2647254/razor_enabled_dotnettest.log)
[razor_enabled_omnisharp.log](https://github.com/aspnet/Razor.VSCode/files/2647256/razor_enabled_omnisharp.log)
[razor_enabled_razor.log](https://github.com/aspnet/Razor.VSCode/files/2647258/razor_enabled_razor.log)
The debugger tries to start but doesn't initialise completely; the debug controls appear but are greyed out:
![screenshot_2018-12-05_11-57-49](https://user-images.githubusercontent.com/17745270/49491081-6d20b900-f885-11e8-9d79-ac94921a15e6.png)

**Comment by NTaylorMullen** [comment]
@gayanW & @walkjivefly thanks for the information! I'll be sure to fix this in our next release!

**Comment by MrCsabaToth** [comment]
This seems to be similar as `https://github.com/dotnet/cli/issues/3390` and

`apt-get install libunwind8`

solved it for me.

**Comment by NTaylorMullen** [comment]
0f40ac8db2b4fd857554a92d1884947abfa0d862

**Comment by NTaylorMullen** [comment]
Reopening this so I can solve this in a different way.

**Comment by NTaylorMullen** [comment]
e06cdf8fc9b8a9dba3b6df97816008320d91f012
