### ISSUE TITLE
Provide information on "Hover"

### ISSUE THREAD

**Issue by akshita31** [aspnet/Razor.VSCode#224]
#### Is this a Bug or Feature request?:
Feature Request

It would be great to have information about the variable in cshtml files when we hover over it.

![hover](https://user-images.githubusercontent.com/12554141/48049531-fc727800-e1c4-11e8-8f18-ab7d163aa6e4.PNG)

**Comment by NTaylorMullen** [comment]
We would love to have this as well 😄. Have another issue tracking this work here: https://github.com/aspnet/Razor.VSCode/issues/27
