### ISSUE TITLE
Coloring is lost on the text following a Razor expression

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#233]
The coloring is fine on the next line.

![image](https://user-images.githubusercontent.com/1579269/48452212-e172ab80-e762-11e8-947b-4e9dec48f59d.png)

VS Code version: 1.28.2
Omnisharp version: 1.17.1
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 3.0.100-preview-009730

**Comment by ajaybhargavb** [comment]
Coloring is also messed up for nested blocks

![image](https://user-images.githubusercontent.com/1579269/48515832-b9448480-e816-11e8-917b-8dc2ca105606.png)

**Comment by NTaylorMullen** [comment]
Closing as duplicate of https://github.com/aspnet/Razor.VSCode/issues/75
