### ISSUE TITLE
Show Razor CSharp/Html Output window doesn't show C# immediately on Linux

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#237]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
Invoke the show Razor C#/Html output

#### Description of the problem:
The window pops up but doesn't show C#/Html

Expected behavior:
C#/Html is shown after invoking the command.

Actual behavior:
C#/Html doesn't show up for a while or until typing.

**Comment by mkArtakMSFT** [comment]
The `Report Razor Issue` handles this for the user, so there is no need to run through multiple windows and collect data manually any more. Having said that, this is really super low priority already, so closing.
