### ISSUE TITLE
No method intellisense inside HTML tags

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#238]
```HTML
<div>@DateTime.Now.Add()</div>
```

Expected:
Intellisense for `Add()`is shown
![image](https://user-images.githubusercontent.com/1579269/48515386-69b18900-e815-11e8-89b0-a7f74b427b0e.png)

Actual:
There is no method intellisense for `Add()`.

VS Code version: 1.29
Omnisharp version: 1.17.1
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 3.0.100-preview-009730

**Comment by NTaylorMullen** [comment]
Super odd. Need to really look into this one.

**Comment by mkArtakMSFT** [comment]
This doesn't repro any more. Closing.
