### ISSUE TITLE
Typing @{ results in @DateTime{}

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#240]
This happens when DateTime is already used somewhere in the document.
When I try to start a Razor code block with `@{`, it autocompletes it to `@DateTime{}`.

Type `@`,
![image](https://user-images.githubusercontent.com/1579269/48516490-5eac2800-e818-11e8-8ba2-06fa10b29836.png)

then type `{`,
![image](https://user-images.githubusercontent.com/1579269/48516531-74b9e880-e818-11e8-8344-1a359a68b5ac.png)

VS Code version: 1.29
Omnisharp version: 1.17.1
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 3.0.100-preview-009730

**Comment by NTaylorMullen** [comment]
We can probably fix this by removing the `{` commit character from completion items when they're following a transition.

**Comment by NTaylorMullen** [comment]
@danroth27 thoughts about this being alpha 3?

**Comment by NTaylorMullen** [comment]
37b4238c2e64866efbc232e203ad117f4b987eaa
