### ISSUE TITLE
Errors disappear after a while

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#241]
The errors in the Problems window disappears after a while of being idle.

VS Code version: 1.29
Omnisharp version: 1.17.1
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 3.0.100-preview-009730

**Comment by NTaylorMullen** [comment]
This is due to the underlying C# virtual buffer being closed out by vscode in an effort to conserve memory. We can workaround this limitation by occasionally pinging the virtual document if it's parent host document is the active editor.

**Comment by mkArtakMSFT** [comment]
Closing as this is super low priority work, we won't get to it ever.
