### ISSUE TITLE
Razor Language Server crashes looking for `System.Runtime.CompilerServices.Unsafe.dll`

### ISSUE THREAD

**Issue by benmiller86** [aspnet/Razor.VSCode#280]
#### Steps to reproduce
Try and run a javascript file with or without debugging (F5/CTRL+F5)

#### Description of the problem:
I get a notification stating:

>The Razor Language Server server creashed 5 times in the last 3 minutes. The server will not be restarted

The "Razor Log" in the output panel shows the same error 5 times:

>[Client - 4:15:34 PM] Starting Razor Language Server...
[Client - 4:15:34 PM] Server started, waiting for client to be ready...
Error:
  An assembly specified in the application dependencies manifest (rzls.deps.json) was not found:
    package: 'System.Runtime.CompilerServices.Unsafe', version: '4.4.0'
    path: 'lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll'
[Info  - 4:07:05 PM] Connection to server got closed. Server will restart.

Followed by:

>[Error - 4:07:05 PM] Connection to server got closed. Server will not be restarted.

#### Expected behavior:

The javascript file should run, and it does if I disable the C# extension.

#### Actual behavior:

The javascript file doesn't run. And I get this errors listed above.

#### Additional information

There are no .cshtml files involved so obviously not including one. I have no idea why the razor language service or even the C# extension are involved to be honest. The errors are only produced on the first run attempt, subsequent attempts just don't do anything. If I had to guess I would say maybe the C# extension is doing something that prevents another extension from starting up that is needed to debug my javascript file?

I have had similar problems with Visual Studio 2017 after a recent update where several of the ASP.NET Core packages couldn't find the `System.Runtime.CompilerServices.Unsafe.dll`, I imagine this is somehow related?

**Comment by NTaylorMullen** [comment]
> I have had similar problems with Visual Studio 2017 after a recent update where several of the ASP.NET Core packages couldn't find the `System.Runtime.CompilerServices.Unsafe.dll`, I imagine this is somehow related?

Yes, I would definitely think so. Would you mind sharing your os/arch (i.e. win10-x64) and the output of `dotnet --info`?

**Comment by NTaylorMullen** [comment]
Very interesting, the only thing I could imagine causing your issues would be a faulty install of omnisharp. Could you try doing a full reinstall of omnisharp. I.e. uninstall it from VSCode, close the ide, go to %UserProfile/.VSCode and delete the omnisharp folder there, open VSCode and install Omnisharp again, try out your project.

If that doesn't resolve your issue you can set the following VSCode setting for that workspace:
`"razor.disabled": true`

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by benmiller86** [comment]
My apologies, I didn't see the earlier suggestion. It would seem that either completely uninstalling the C# extension as above or updates to VS Code or the C# extension have resolved my issue. Thank you for your time.
