### ISSUE TITLE
Add hashed reference assemblies and file extensions of .NET projects to telemetry.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#284]
Hashing can be done using this service: https://github.com/aspnet/Tooling-Internal/blob/master/telemetry-scripts/andrehal/ScopeQueries/src/Queries.CSharp/DataGridQueries.CSharp/HashingService.cs

**Comment by NTaylorMullen** [comment]
@rchande I can close this out because you guys are taking ownership of this right?

**Comment by rchande** [comment]
@NTaylorMullen Yep! Copied to https://github.com/OmniSharp/omnisharp-roslyn/issues/1402
