### ISSUE TITLE
Support TagHelper

### ISSUE THREAD

**Issue by tgemelgo** [aspnet/Razor.VSCode#311]
Today VSCode does not support TagHelper, ie I can not develop custom taghelper for my application and interact with VSCode, I would like to know if there is any forecast to support this functionality

**Comment by NTaylorMullen** [comment]
@tgemelgo, some basic TagHelper support (completions for instance) will be added in the next release (alpha3). That release is currently planned to be shipped sometime end of april. Stay tuned!
