### ISSUE TITLE
Html linting

### ISSUE THREAD

**Issue by guylando** [aspnet/Razor.VSCode#329]
#### Is this a Bug or Feature request?:

Bug + Feature request

#### Steps to reproduce

inside a cshtml file write:
`<ol>aasada</ol>`

or write
`<ol><li>asas</ol>`

#### Description of the problem:

Html linting does not work

#### Expected behavior:

Display errors about invalid html.

#### Actual behavior:

No errors displayed

#### Additional information

Using latest version of vscode and of all extensions.

**Comment by NTaylorMullen** [comment]
@guylando thanks for the bug report! Do you see HTML linting in normal HTML files within VSCode?

**Comment by guylando** [comment]
No built-in linting for HTML. If to install https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint extension and change cshtml extension to html then there is some linting but very partial linting (no linting for the `<ol>aaaa</ol>` problem for example)

**Comment by NTaylorMullen** [comment]
I see. Adding better support for extensions adding errors/warnings for CSHTMl files through .html files is definitely on our roadmap but there are a few pre-requisites we need to tackle first. First issue we'll need to tackle is: https://github.com/aspnet/Razor.VSCode/issues/99. That way when an error is logged for a document we're tracking (we generate fake html documents already) we can lift the errors for that document and display them in the CSHTML doc.

**Comment by guylando** [comment]
Vscode prettier, eslint, stylelint extensions work great and html linting (and maybe auto fixing) is not less important. Maybe can take example from the css/js handling in those extensions which seems to already work well with vscode.
Thanks for your answer.

**Comment by NTaylorMullen** [comment]
Definitely will do, thanks @guylando! Closing this issue out for now in preference of #99 :smile:
