### ISSUE TITLE
On Document renamed that was open the old C# buffer sticks around.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#344]
After a rename you might get phantom errors about the previously named document until VSCode kills the virtual document.

**Comment by NTaylorMullen** [comment]
@danroth27 do you think this is needed for alpha3? I put it there for now but i'm not entirely convinced because this has always been an issue. My only concern comes from the need for people to rename `_ViewImports.cshtml` to `_Imports.razor` files and then having phantom errors for a bit.

**Comment by danroth27** [comment]
How long do the phantom errors stick around?

**Comment by NTaylorMullen** [comment]
Could be forever if you don't do much in your editor. It's indeterminate because VSCode controls the lifetime of the virtual buffers. If the user is jumping through files a lot VSCode will typically throw the virtual buffers away within the minute because other documents are being opened.

**Comment by danroth27** [comment]
It sounds like this would be nice to have in alpha3 for folks migrating apps from a previous preview, but not so important for folks starting from scratch. For VS Code I'm more concerned with folks having a good intro to Blazor, so I'm not too concerned if you want to push this out of alpha3.

**Comment by NTaylorMullen** [comment]
a47442ff240bc6a5096614ec7cb24f645f16f8ef
