### ISSUE TITLE
HTML Tag Coloring with in-line Razor code

### ISSUE THREAD

**Issue by stquinton** [aspnet/Razor.VSCode#368]
## Is this a Bug or Feature request?:
Bug

## Steps to reproduce
1. Create an opening html tag
2. Enter a Razor command
3. Create the closing HTML tag on the same line

## Description of the problem:
When an opening and closing HTML tag are on the same line with a Razor command, the closing tag does not receive the proper coloring. If you separate the tags onto different lines, the colors are correct.

Expected behavior:
The closing tag should have appropriate HTML color formatting.

Actual behavior:
The closing tag does not have the appropriate HTML color formatting.

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 4:45:42 PM] -- Starting Issue Data Collection-- 
[Client - 4:45:45 PM] -- Stopping Issue Data Collection-- 
```

</p>
</details>

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>


////////////////////// Projected Html as seen by VSCode ///////////////////////
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>
// 51
```

</p>
</details>

## Machine information

**VSCode version**: 1.35.0
**Razor.VSCode version**: 1.19.1
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|markdown-all-in-one|yzhang|2.3.1|
|mssql|ms-mssql|1.6.0|
|powershell|ms-vscode|2019.5.0|
|python|ms-python|2019.5.18426|
|vba|spences10|1.2.0|
|vscode-tfs|ivangabriele|0.7.2|;

</p>
</details>

**Comment by NTaylorMullen** [comment]
@stquinton thanks for the report! We happen to be tracking the fix to this issue [here](https://github.com/aspnet/Razor.VSCode/issues/75). Going to close this as a dup for now.
