### ISSUE TITLE
Plans / commitment to support Blazor?

### ISSUE THREAD

**Issue by srowan** [aspnet/Razor.VSCode#388]
Is this a Bug or Feature request?: **Feature**

From what I can tell, vscode has not been keeping up with blazor updates.  For example the `@code { }` block added in preview 6 (2 months ago) isn't being picked up, coloring and intellisense isn't really working, and errors aren't highlighted in razor files.

Is there any guidance on what level of support we might get for Blazor in VSCode moving forward?  Any estimated timelines?  

Perhaps the wrong place to ask this, but if not vscode, can we expect parity in Visual Studio for Mac?  This is an important issue for teams with Mac developers.  Perhaps my real question is: Is there a practical future for professional Blazor development on Mac?

**Comment by NTaylorMullen** [comment]
Hey @srowan, glad you're interested in Blazor support for VSCode 😄. 

In VSCode, coloring is just a facade and doesn't result in any actual errors. Also, any editor interactions in discolored areas will still result in proper completion, IntelliSense etc. 

In regards to Blazor support in VSCode, we make sure to release latest Razor/Blazor support for VSCode every release. This typically involves new language features such as directive attributes (`@onclick`), new components etc.

Allll of that being said, we're tracking the fix to coloring over [here](https://github.com/aspnet/Razor.VSCode/issues/75), stay tuned!
