### ISSUE TITLE
Razor comment  TextMate display incorrectly when it includes html tag

### ISSUE THREAD

**Issue by larryw3i** [aspnet/Razor.VSCode#391]
Razor comment  TextMate display incorrectly when it includes html tag >_    

<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-08-13%2013-42-40_.webp'/>

**Comment by NTaylorMullen** [comment]
Thanks @larryw3i for the specifics! These are all great finds that I'll ensure I address as part of https://github.com/aspnet/Razor.VSCode/issues/75. Going to close this as a duplicate for now.
