### ISSUE TITLE
Razor comment TextMate display incorrectly when "@if" is used

### ISSUE THREAD

**Issue by larryw3i** [aspnet/Razor.VSCode#406]
<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-09-18%2021-07-48.webp'/>

**Comment by NTaylorMullen** [comment]
Haha, look at that. Nice catch 😄. Going to close this as a duplicate of https://github.com/aspnet/Razor.VSCode/issues/75. Me linking to that issue will ensure we cover this scenario when we fix Razor's textmate grammar.
